/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m03.uf6.p1.grup07.controlador;

/**
 *
 * @author adri
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.*;
import m03.uf6.p1.grup07.vista.RenderizadorCeldas;

/**
 *
 * @author jmartin
 */
public class SelectorPacients extends javax.swing.JFrame {

    /**
     * Creates new form SelectorJugadores
     */
    public SelectorPacients() {
        initComponents();
        Pacients.removeAllItems();
        TableModel modelBuit = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
            },
            new String [] {
                "nom", "cognom1", "cognom2", "numSegSocial", "NIF", "telefon", "codiHistorial"
            }
        );
        
        tabPacients.setModel(modelBuit);
        RenderizadorCeldas renderizador = new RenderizadorCeldas();
        for (int i = 0; i < tabPacients.getColumnCount(); i++) {
            tabPacients.getColumnModel().getColumn(i).setCellRenderer(renderizador);
        }
        
        try{
            ResultSet resultat = consultaBBDD("SELECT NIF FROM PACIENTS");
            Pacients.addItem(null);
            while(resultat.next()){
                Pacients.addItem(resultat.getString("NIF"));
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    private ResultSet consultaBBDD(String consultaSQL) throws SQLException{
        
        Connection con = null;
        Statement sentencia = null;
        ResultSet resultat = null;
        try{
            con = GestorConnexio.getConnection();
            sentencia = con.createStatement();
            sentencia.executeQuery(consultaSQL);
            resultat = sentencia.getResultSet();
        }catch(SQLException e){
            e.printStackTrace();
        }
        return resultat;
    }
    
    private void actualitzaTaula(JTable taula, TableModel model){
        taula.setModel(model);
        RenderizadorCeldas renderizador = new RenderizadorCeldas();
        for (int i = 0; i < taula.getColumnCount(); i++) {
            taula.getColumnModel().getColumn(i).setCellRenderer(renderizador);
        }
        // Nom mostrarem la columna id a la taula, però la necessitem per fer el update
        // si editem un camp
        TableColumnModel tcm = taula.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Pacients = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPacients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pacients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientsActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoja un equipo");

        tabPacients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabPacients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pacients, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pacients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void PacientsActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(Pacients.getSelectedIndex() < 0){
            // Nada que hacer
        }else{
            String pacients = (String)(Pacients.getSelectedItem());
            try{
                ResultSet resultat = consultaBBDD(
                        //"SELECT jugadores.nombre, jugadores.dorsal, jugadores.edad"
                        "SELECT * FROM PACIENTS "
                                + "WHERE pacients.NIF LIKE '" + pacients + "'");
                TableModel model = new ModeloDeTablaSimple(resultat);
                actualitzaTaula(tabPacients, model);
                // Afegim un listener per salvar els canvis a la BBDD en modificar
                // el valor d'un camp de la taula
                tabPacients.getModel().addTableModelListener(new TableModelListener() {
                    @Override
                    public void tableChanged(TableModelEvent e) {
                        actualitzaTaulaPacients(e);
                    }
                });
                
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }                                         

    private void actualitzaTaulaPacients(TableModelEvent e){
        int fila = e.getFirstRow();
        PreparedStatement sentencia = null;
        Connection con = null;
        TableModel dades = tabPacients.getModel();
        try {
            con = GestorConnexio.getConnection();
            String consulta = "UPDATE pacients SET nom = ?, cognom1 = ?, "
              + "cognom2 = ?, numSegSocial = ?, NIF = ?, telefon = ? WHERE NIF = ?";
            sentencia = con.prepareStatement(consulta);
            sentencia.setString(1, (String)(dades.getValueAt(fila, 0)));
            sentencia.setString(2, (String)(dades.getValueAt(fila, 1)));
            sentencia.setString(3, (String)(dades.getValueAt(fila, 2)));
            sentencia.setString(4, (String)(dades.getValueAt(fila, 3)));
            sentencia.setString(5, (String)(dades.getValueAt(fila, 4)));
            sentencia.setInt(6, Integer.parseInt(dades.getValueAt(fila, 5).toString()));
            sentencia.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(SelectorMetges.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorMetges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorMetges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorMetges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorMetges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorPacients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox Pacients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPacients;
    // End of variables declaration                   
}

